config/routes.rb
Traffic::Application.routes.draw do
  resources :weathers

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :collisions

end

app/models/collision.rb
class Collision < ActiveRecord::Base
end

app/models/weather.rb
class Weather < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/collisions_controller.rb
class CollisionsController < ApplicationController
  before_action :set_collision, only: [:show, :edit, :update, :destroy]

  def index
    @collisions = Collision.all
  end

  def show
  end

  def new
    @collision = Collision.new
  end

  def edit
  end

  def create
    @collision = Collision.new(collision_params)

    respond_to do |format|
      if @collision.save
        format.html { redirect_to @collision, notice: 'Collision was successfully created.' }
        format.json { render action: 'show', status: :created, location: @collision }
      else
        format.html { render action: 'new' }
        format.json { render json: @collision.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @collision.update(collision_params)
        format.html { redirect_to @collision, notice: 'Collision was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @collision.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @collision.destroy
    respond_to do |format|
      format.html { redirect_to collisions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collision
      @collision = Collision.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collision_params
      params.require(:collision).permit(:date_of_collision, :time_of_collision, :location, :collision_type, :involved_with, :vehicle_one_direction, :vechicle_one_motion, :vehicle_two_direction, :vehicle_two_motion, :primary_cause, :injuries, :fatalities, :distance,:weather_condition)
    end
end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  before_action :set_weather, only: [:show, :edit, :update, :destroy]

  # GET /weathers
  # GET /weathers.json
  def index
    @weathers = Weather.all
  end

  # GET /weathers/1
  # GET /weathers/1.json
  def show
  end

  # GET /weathers/new
  def new
    @weather = Weather.new
  end

  # GET /weathers/1/edit
  def edit
  end

  # POST /weathers
  # POST /weathers.json
  def create
    @weather = Weather.new(weather_params)

    respond_to do |format|
      if @weather.save
        format.html { redirect_to @weather, notice: 'Weather was successfully created.' }
        format.json { render action: 'show', status: :created, location: @weather }
      else
        format.html { render action: 'new' }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weathers/1
  # PATCH/PUT /weathers/1.json
  def update
    respond_to do |format|
      if @weather.update(weather_params)
        format.html { redirect_to @weather, notice: 'Weather was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weathers/1
  # DELETE /weathers/1.json
  def destroy
    @weather.destroy
    respond_to do |format|
      format.html { redirect_to weathers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weather
      @weather = Weather.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weather_params
      params.require(:weather).permit(:weather_date, :condition)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collisions_helper.rb
module CollisionsHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/collisions/_form.html.erb
<%= form_for(@collision) do |f| %>
  <% if @collision.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collision.errors.count, "error") %> prohibited this collision from being saved:</h2>

      <ul>
      <% @collision.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_of_collision %><br>
    <%= f.text_field :date_of_collision %>
  </div>
  <div class="field">
    <%= f.label :time_of_collision %><br>
    <%= f.text_field :time_of_collision %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :collision_type %><br>
    <%= f.text_field :collision_type %>
  </div>
  <div class="field">
    <%= f.label :involved_with %><br>
    <%= f.text_field :involved_with %>
  </div>
  <div class="field">
    <%= f.label :vehicle_one_direction %><br>
    <%= f.text_field :vehicle_one_direction %>
  </div>
  <div class="field">
    <%= f.label :vechicle_one_motion %><br>
    <%= f.text_field :vechicle_one_motion %>
  </div>
  <div class="field">
    <%= f.label :vehicle_two_direction %><br>
    <%= f.text_field :vehicle_two_direction %>
  </div>
  <div class="field">
    <%= f.label :vehicle_two_motion %><br>
    <%= f.text_field :vehicle_two_motion %>
  </div>
  <div class="field">
    <%= f.label :primary_cause %><br>
    <%= f.text_field :primary_cause %>
  </div>
  <div class="field">
    <%= f.label :injuries %><br>
    <%= f.number_field :injuries %>
  </div>
  <div class="field">
    <%= f.label :fatalities %><br>
    <%= f.number_field :fatalities %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collisions/edit.html.erb
<h1>Editing collision</h1>

<%= render 'form' %>

<%= link_to 'Show', @collision %> |
<%= link_to 'Back', collisions_path %>

app/views/collisions/index.html.erb
<h1>Listing collisions</h1>

<table>
  <thead>
    <tr>
      <th>Date of collision</th>
      <th>Time of collision</th>
      <th>Location</th>
      <th>Collision type</th>
      <th>Involved with</th>
      <th>Vehicle one direction</th>
      <th>Vechicle one motion</th>
      <th>Vehicle two direction</th>
      <th>Vehicle two motion</th>
      <th>Primary cause</th>
      <th>Injuries</th>
      <th>Fatalities</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @collisions.each do |collision| %>
      <tr>
        <td><%= collision.date_of_collision %></td>
        <td><%= collision.time_of_collision %></td>
        <td><%= collision.location %></td>
        <td><%= collision.collision_type %></td>
        <td><%= collision.involved_with %></td>
        <td><%= collision.vehicle_one_direction %></td>
        <td><%= collision.vechicle_one_motion %></td>
        <td><%= collision.vehicle_two_direction %></td>
        <td><%= collision.vehicle_two_motion %></td>
        <td><%= collision.primary_cause %></td>
        <td><%= collision.injuries %></td>
        <td><%= collision.fatalities %></td>
        <td><%= link_to 'Show', collision %></td>
        <td><%= link_to 'Edit', edit_collision_path(collision) %></td>
        <td><%= link_to 'Destroy', collision, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collision', new_collision_path %>

app/views/collisions/new.html.erb
<h1>New collision</h1>

<%= render 'form' %>

<%= link_to 'Back', collisions_path %>

app/views/collisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date of collision:</strong>
  <%= @collision.date_of_collision %>
</p>

<p>
  <strong>Time of collision:</strong>
  <%= @collision.time_of_collision %>
</p>

<p>
  <strong>Location:</strong>
  <%= @collision.location %>
</p>

<p>
  <strong>Collision type:</strong>
  <%= @collision.collision_type %>
</p>

<p>
  <strong>Involved with:</strong>
  <%= @collision.involved_with %>
</p>

<p>
  <strong>Vehicle one direction:</strong>
  <%= @collision.vehicle_one_direction %>
</p>

<p>
  <strong>Vechicle one motion:</strong>
  <%= @collision.vechicle_one_motion %>
</p>

<p>
  <strong>Vehicle two direction:</strong>
  <%= @collision.vehicle_two_direction %>
</p>

<p>
  <strong>Vehicle two motion:</strong>
  <%= @collision.vehicle_two_motion %>
</p>

<p>
  <strong>Primary cause:</strong>
  <%= @collision.primary_cause %>
</p>

<p>
  <strong>Injuries:</strong>
  <%= @collision.injuries %>
</p>

<p>
  <strong>Fatalities:</strong>
  <%= @collision.fatalities %>
</p>

<%= link_to 'Edit', edit_collision_path(@collision) %> |
<%= link_to 'Back', collisions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Traffic</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/weathers/_form.html.erb
<%= form_for(@weather) do |f| %>
  <% if @weather.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weather.errors.count, "error") %> prohibited this weather from being saved:</h2>

      <ul>
      <% @weather.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :weather_date %><br>
    <%= f.text_field :weather_date %>
  </div>
  <div class="field">
    <%= f.label :condition %><br>
    <%= f.text_field :condition %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weathers/edit.html.erb
<h1>Editing weather</h1>

<%= render 'form' %>

<%= link_to 'Show', @weather %> |
<%= link_to 'Back', weathers_path %>

app/views/weathers/index.html.erb
<h1>Listing weathers</h1>

<table>
  <thead>
    <tr>
      <th>Weather date</th>
      <th>Condition</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @weathers.each do |weather| %>
      <tr>
        <td><%= weather.weather_date %></td>
        <td><%= weather.condition %></td>
        <td><%= link_to 'Show', weather %></td>
        <td><%= link_to 'Edit', edit_weather_path(weather) %></td>
        <td><%= link_to 'Destroy', weather, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weather', new_weather_path %>

app/views/weathers/new.html.erb
<h1>New weather</h1>

<%= render 'form' %>

<%= link_to 'Back', weathers_path %>

app/views/weathers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weather date:</strong>
  <%= @weather.weather_date %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @weather.condition %>
</p>

<%= link_to 'Edit', edit_weather_path(@weather) %> |
<%= link_to 'Back', weathers_path %>